# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rover.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brover.proto\" \n\nMapRequest\x12\x12\n\nrover_name\x18\x01 \x02(\t\"\x1a\n\x0bMapResponse\x12\x0b\n\x03map\x18\x01 \x02(\t\"#\n\x0cMovesRequest\x12\x13\n\x0brover_index\x18\x01 \x02(\t\"\x1e\n\rMovesResponse\x12\r\n\x05moves\x18\x01 \x02(\t\"?\n\x14MineSerialNumRequest\x12\x13\n\x0brover_index\x18\x01 \x02(\t\x12\x12\n\nmine_coord\x18\x02 \x02(\t\"E\n\x15MineSerialNumResponse\x12\x13\n\x0brover_index\x18\x01 \x02(\t\x12\x17\n\x0fmine_serial_num\x18\x02 \x02(\t\"/\n\x18\x43ompletedCommandsRequest\x12\x13\n\x0brover_index\x18\x01 \x02(\t\",\n\x19\x43ompletedCommandsResponse\x12\x0f\n\x07message\x18\x01 \x02(\t\"<\n\x13ShareMinePinRequest\x12\x13\n\x0brover_index\x18\x01 \x02(\t\x12\x10\n\x08mine_pin\x18\x02 \x02(\t\"\'\n\x14ShareMinePinResponse\x12\x0f\n\x07message\x18\x01 \x02(\t2\xbe\x02\n\x05Rover\x12%\n\x06GetMap\x12\x0b.MapRequest\x1a\x0c.MapResponse\"\x00\x12\x36\n\x13GetStreamOfCommands\x12\r.MovesRequest\x1a\x0e.MovesResponse\"\x00\x12\x46\n\x13GetMineSerialNumber\x12\x15.MineSerialNumRequest\x1a\x16.MineSerialNumResponse\"\x00\x12O\n\x14SayCompletedCommands\x12\x19.CompletedCommandsRequest\x1a\x1a.CompletedCommandsResponse\"\x00\x12=\n\x0cShareMinePin\x12\x14.ShareMinePinRequest\x1a\x15.ShareMinePinResponse\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rover_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPREQUEST._serialized_start=15
  _MAPREQUEST._serialized_end=47
  _MAPRESPONSE._serialized_start=49
  _MAPRESPONSE._serialized_end=75
  _MOVESREQUEST._serialized_start=77
  _MOVESREQUEST._serialized_end=112
  _MOVESRESPONSE._serialized_start=114
  _MOVESRESPONSE._serialized_end=144
  _MINESERIALNUMREQUEST._serialized_start=146
  _MINESERIALNUMREQUEST._serialized_end=209
  _MINESERIALNUMRESPONSE._serialized_start=211
  _MINESERIALNUMRESPONSE._serialized_end=280
  _COMPLETEDCOMMANDSREQUEST._serialized_start=282
  _COMPLETEDCOMMANDSREQUEST._serialized_end=329
  _COMPLETEDCOMMANDSRESPONSE._serialized_start=331
  _COMPLETEDCOMMANDSRESPONSE._serialized_end=375
  _SHAREMINEPINREQUEST._serialized_start=377
  _SHAREMINEPINREQUEST._serialized_end=437
  _SHAREMINEPINRESPONSE._serialized_start=439
  _SHAREMINEPINRESPONSE._serialized_end=478
  _ROVER._serialized_start=481
  _ROVER._serialized_end=799
# @@protoc_insertion_point(module_scope)
