# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rover_pb2 as rover__pb2


class RoverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/Rover/GetMap',
                request_serializer=rover__pb2.MapRequest.SerializeToString,
                response_deserializer=rover__pb2.MapResponse.FromString,
                )
        self.GetStreamOfCommands = channel.unary_unary(
                '/Rover/GetStreamOfCommands',
                request_serializer=rover__pb2.MovesRequest.SerializeToString,
                response_deserializer=rover__pb2.MovesResponse.FromString,
                )
        self.GetMineSerialNumber = channel.unary_unary(
                '/Rover/GetMineSerialNumber',
                request_serializer=rover__pb2.MineSerialNumRequest.SerializeToString,
                response_deserializer=rover__pb2.MineSerialNumResponse.FromString,
                )
        self.SayCompletedCommands = channel.unary_unary(
                '/Rover/SayCompletedCommands',
                request_serializer=rover__pb2.CompletedCommandsRequest.SerializeToString,
                response_deserializer=rover__pb2.CompletedCommandsResponse.FromString,
                )
        self.ShareMinePin = channel.unary_unary(
                '/Rover/ShareMinePin',
                request_serializer=rover__pb2.ShareMinePinRequest.SerializeToString,
                response_deserializer=rover__pb2.ShareMinePinResponse.FromString,
                )


class RoverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamOfCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMineSerialNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayCompletedCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareMinePin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=rover__pb2.MapRequest.FromString,
                    response_serializer=rover__pb2.MapResponse.SerializeToString,
            ),
            'GetStreamOfCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamOfCommands,
                    request_deserializer=rover__pb2.MovesRequest.FromString,
                    response_serializer=rover__pb2.MovesResponse.SerializeToString,
            ),
            'GetMineSerialNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMineSerialNumber,
                    request_deserializer=rover__pb2.MineSerialNumRequest.FromString,
                    response_serializer=rover__pb2.MineSerialNumResponse.SerializeToString,
            ),
            'SayCompletedCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.SayCompletedCommands,
                    request_deserializer=rover__pb2.CompletedCommandsRequest.FromString,
                    response_serializer=rover__pb2.CompletedCommandsResponse.SerializeToString,
            ),
            'ShareMinePin': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareMinePin,
                    request_deserializer=rover__pb2.ShareMinePinRequest.FromString,
                    response_serializer=rover__pb2.ShareMinePinResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Rover', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Rover(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Rover/GetMap',
            rover__pb2.MapRequest.SerializeToString,
            rover__pb2.MapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStreamOfCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Rover/GetStreamOfCommands',
            rover__pb2.MovesRequest.SerializeToString,
            rover__pb2.MovesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMineSerialNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Rover/GetMineSerialNumber',
            rover__pb2.MineSerialNumRequest.SerializeToString,
            rover__pb2.MineSerialNumResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayCompletedCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Rover/SayCompletedCommands',
            rover__pb2.CompletedCommandsRequest.SerializeToString,
            rover__pb2.CompletedCommandsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ShareMinePin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Rover/ShareMinePin',
            rover__pb2.ShareMinePinRequest.SerializeToString,
            rover__pb2.ShareMinePinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
